version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_DATABASE=urlshortener
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_WORKER_USERNAME=${MONGODB_WORKER_USER}
      - MONGO_INITDB_WORKER_PASSWORD=${MONGODB_WORKER_PASSWORD}
    ports:
      - $MONGODB_LOCAL_PORT:27017
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  app:
    image: vqus
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb
      - backend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./app:/usr/src/app:delegated"
      - /usr/src/app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    volumes:
      - ./backend:/usr/src/backend:delegated
      - /usr/src/backend/node_modules
    env_file: ./.env
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    ports:
      - "5200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - backend

volumes:
  mongodb_data: